name: clean_news_ai
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 0.1.2
  worker_manager: ^2.0.8
  osam: ^2.3.7
  flutter_sticky_header: ^0.4.0
  sliver_animated_list: ^1.0.0+2
  path_provider:
  hive:
  hive_flutter:
  http:
  intl:
  share:
  uuid:

dev_dependencies:
  hive_generator:
    git:
      url: https://github.com/Renesanse/hive_generator.git
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
